version: "3.7"

services:
    rust:
      image: rust:buster
      container_name: cngateway
      volumes: 
        - .:/tmp/cngateway
      working_dir: /tmp/cngateway
      networks:
        - cyphernodeappsnet
      
      command: tail -f "/dev/null"

networks:
  cyphernodeappsnet:
    external: true